### ISSUE TITLE
Not getting a cytoplasm mask

### ISSUE THREAD

**Issue by Lottieswinyard** [HMS-IDAC/S3segmenter#8]
Hi, 

I am using s3segmenter as part of MCMICRO pipeline and would like to segment the nuclei and cytoplasm. The nuclei mask is working beautifully however I am not getting a cytoplasm mask out, not even a cytoplasm.ome.tif file (just cell and nuclei which look the same as each other). 

I have added: 

S3seg-opts: '--nucleiRegion localMax --CytoMaskChan 30 --segmentCytoplasm segmentCytoplasm --cytoMethod hybrid --cytoDilation 10'

To my params.yml file. Is there something I have done wrong? 

Thanks, Ottilie

**Comment by ArtemSokolov** [comment]
Hi Ottilie,

Not sure if it's just a simple typo, but `s3seg-opts` should be all lowercase.

You can also check to make sure the parameters get passed to S3segmenter. You can do this after `nextflow run` finishes by using `nextflow log last -f name,workdir` to identify which modules used which work directories. Inside the s3seg work directory you will find a file called `.command.sh` (may appear hidden on a linux system). This file will contain the exact command being executed inside the container. Check to make sure that it has all your parameters from `s3seg-opts`.

**Comment by Lottieswinyard** [comment]
Ah thank you so much @ArtemSokolov - It has indeed worked with the lower case in params.yml, Brilliant!

(Just a note - on mcmicro.org > parameter tuning > S3segmenter the examples in there are capitals for S3segmenter, possibly an outdated version) 

Thanks again!

**Comment by ArtemSokolov** [comment]
Thank you, @Lottieswinyard 
Great catch! This will be fixed in the next iteration of the documentation.
